// Codegen - Record and playback tool. It is a built in Playwright tool.
// It helps to generate code by recording user actions on the browser.


// To run codegen use the below command in the terminal
// npx playwright codegen "<website URL>"

import { test, expect } from '@playwright/test';

test('Login generated by codegen', async ({ page }) => {
  await page.goto('https://practicetestautomation.com/practice-test-login/');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('student');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Password123');
  await expect(page.getByRole('textbox', { name: 'Password' })).toHaveValue('Password123');
  await page.getByRole('button', { name: 'Submit' }).click();
  await expect(page.getByRole('heading')).toContainText('Successfully');
  await expect(page.getByRole('link', { name: 'Log out' })).toBeVisible();
});

test('Frames handling by codegen', async ({ page }) => {

  await page.goto('https://demo.automationtesting.in/Frames.html');

  await page.locator('iframe[name="SingleFrame"]').contentFrame().getByRole('textbox').click();
  await page.locator('iframe[name="SingleFrame"]').contentFrame().getByRole('textbox').fill('Single Frame');
  await expect(page.locator('iframe[name="SingleFrame"]').contentFrame().getByRole('textbox')).toHaveValue('Single Frame');

  await page.getByRole('link', { name: 'Iframe with in an Iframe' }).click();
  
  await page.locator('#Multiple').getByText('<p>Your browser does not').contentFrame().getByText('<p>Your browser does not').contentFrame().getByRole('textbox').click();
  await page.locator('#Multiple').getByText('<p>Your browser does not').contentFrame().getByText('<p>Your browser does not').contentFrame().getByRole('textbox').fill('Nested Frames');
  await expect(page.locator('#Multiple').getByText('<p>Your browser does not').contentFrame().getByText('<p>Your browser does not').contentFrame().getByRole('textbox')).toHaveValue('Nested Frames');
});
